# Совместим с L4T R36.5.0 (JetPack 6.2.2)
FROM dustynv/ros:humble-desktop-l4t-r36.4.0

ENV DEBIAN_FRONTEND=noninteractive
ENV ROS_DISTRO=humble
ENV CUDA_ARCHITECTURES="87"

# Фикс для QEMU: ldconfig не работает в эмуляции
RUN dpkg-divert --add --rename --divert /sbin/ldconfig.real /sbin/ldconfig \
    && echo '#!/bin/sh\nexit 0' > /sbin/ldconfig \
    && chmod +x /sbin/ldconfig

# Доп. зависимости для сборки ROS-пакетов
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    cmake \
    pkg-config \
    git \
    wget \
    python3-colcon-common-extensions \
    python3-rosdep \
    libpcl-dev \
    libeigen3-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace
ENV PATH="/opt/ros/${ROS_DISTRO}/bin:${PATH}"
